require 'sqlite3'

def seed_recipes_db(recipes_db, recipes)
	recipes.each do |recipe|
		recipes_db.execute("INSERT INTO recipes (name, source, type, cook_time_hr, diet_vegan) 
			VALUES (?, ?, ?, ?, ?)", recipe)
	end
end

def seed_ingredients_db(recipes_db, ingredients)
	ingredients.each do |recipe_ingredients|
		recipes_db.execute("INSERT INTO ingredients (
			spinach_baby_cup,
			celery_hd,
			green_onion_ct,
			lime_ct,
			lemon_ct,
			onion_yellow_ct,
			onion_red_ct,
			potato_sweet_ct,
			potato_red_ct,
			garlic_clv,
			broccoli_ct,
			carrot_ct,
			squash_zucchini_ct,
			leeks_ct,
			ginger_inch,
			squash_yellow_ct,
			asparagus_bnch,
			greenbean_cup,
			tomato_cherry_cup,
			pepper_red_bell_ct,
			pepper_green_bell_ct,
			pepper_serrano_ct,
			herb_basil_cup,
			herb_parsley_cup,
			herb_cilantro_cup,
			quinoa_cup,
			lentil_cup,
			sugar_white_cup,
			sugar_brown_cup,
			flour_ap_cup,
			lentil_yellow_cup,
			rice_arborio_cup,
			red_pepper_flakes_tb,
			pepper_black_tb,
			garlic_powder_tb,
			curry_powder_tb,
			blend_italian_tb,
			salt_kosher_tb,
			salt_sea_tb,
			sausage_italian_lb,
			can_chickpea_oz,
			can_tomatoes_diced_oz,
			broth_vegetable_cup,
			cond_mustard_dijon_cup,
			oil_olive_tb,
			oil_canola_tb,
			vinegar_red_wine_cup,
			vinegar_balsamic_cup,
			pasta_short_oz,
			chocolate_dark_oz,
			ethnic_coconut_milk_oz,
			butter_unsalted_cup,
			eggs_ct,
			cheese_parm_regg_tb,
			cheese_romano_cup,
			wine_white_dry_cup,
			recipe_id) 
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
			?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", 
			recipe_ingredients)
	end
end

recipes_db = SQLite3::Database.new("recipes.db")
recipes_db.results_as_hash = true

create_recipe_table_cmd = <<-SQL
  CREATE TABLE IF NOT EXISTS recipes(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    source VARCHAR(255),
    type VARCHAR(255),
    cook_time_hr REAL,
    diet_vegan BOOLEAN
  )
SQL

create_ingredients_table_cmd = <<-SQL
  CREATE TABLE IF NOT EXISTS ingredients(
    id INTEGER PRIMARY KEY,
	spinach_baby_cup REAL,
	celery_hd REAL,
	green_onion_ct REAL,
	lime_ct REAL,
	lemon_ct REAL,
	onion_yellow_ct REAL,
	onion_red_ct REAL,
	potato_sweet_ct REAL,
	potato_red_ct REAL,
	garlic_clv REAL,
	broccoli_ct REAL,
	carrot_ct REAL,
	squash_zucchini_ct REAL,
	leeks_ct REAL,
	ginger_inch REAL,
	squash_yellow_ct REAL,
	asparagus_bnch REAL,
	greenbean_cup REAL,
	tomato_cherry_cup REAL,
	pepper_red_bell_ct REAL,
	pepper_green_bell_ct REAL,
	pepper_serrano_ct REAL,
	herb_basil_cup REAL,
	herb_parsley_cup REAL,
	herb_cilantro_cup REAL,
	quinoa_cup REAL,
	lentil_cup REAL,
	sugar_white_cup REAL,
	sugar_brown_cup REAL,
	flour_ap_cup REAL,
	lentil_yellow_cup REAL,
	rice_arborio_cup REAL,
	red_pepper_flakes_tb REAL,
	pepper_black_tb REAL,
	garlic_powder_tb REAL,
	curry_powder_tb REAL,
	blend_italian_tb REAL,
	salt_kosher_tb REAL,
	salt_sea_tb REAL,
	sausage_italian_lb REAL,
	can_chickpea_oz REAL,
	can_tomatoes_diced_oz REAL,
	broth_vegetable_cup REAL,
	cond_mustard_dijon_cup REAL,
	oil_olive_tb REAL,
	oil_canola_tb REAL,	
	vinegar_red_wine_cup REAL,
	vinegar_balsamic_cup REAL,
	pasta_short_oz REAL,
	chocolate_dark_oz REAL,
	ethnic_coconut_milk_oz REAL,
	butter_unsalted_cup REAL,
	eggs_ct REAL,
	cheese_parm_regg_tb REAL,
	cheese_romano_cup REAL,
	wine_white_dry_cup REAL,
	recipe_id INTEGER,
	FOREIGN KEY(recipe_id) REFERENCES recipes(id)
  );
SQL



recipes = [

	[
		"Slow-Cooker Vegetable Chickpea Curry",
		"MyRecipes",
		"Entree",
	    "6.5",
	    "true"
	],

	[
		"No-Cream Pasta Primavera",
		"AllRecipes",
		"Entree",
	    "1",
	    "false"
	],

	[
		"Tomato and Sausage Risotto",
		"Smitten Kitchen",
		"Entree",
	    "1",
	    "false"
	],

	[
		"Lentil Quinoa Salad",
		"Food Network",
		"Salad",
	    "0.75",
	    "true"
	],

	[
		"Slow-Cooker Sweet Potato and Lentil Soup",
		"Food Network",
		"Soup",
	    "8.5",
	    "true"
	],

	[
		"Almost Flourless Chocolate Cake",
		"Food52",
		"Dessert",
	    "1",
	    "false"
	],

	[
		"Slow-Baked Broccoli Frittata",
		"Food52",
		"Breakfast",
	    "1",
	    "false"
	]

]

ingredients = [
	[
	3, # spinach_baby_cup REAL,
	0, # celery_hd REAL,
	0, # green_onion_ct REAL,
	0, # lime_ct REAL,
	1, # lemon_ct REAL,
	1, # onion_yellow_ct REAL,
	0, # onion_red_ct REAL,
	0, # potato_sweet_ct REAL,
	6, # potato_red_ct REAL,
	2, # garlic_clv REAL,
	0, # broccoli_ct REAL,
	2, # carrot_ct REAL,
	0, # squash_zucchini_ct REAL,
	0, # leeks_ct REAL,
	1, # ginger_inch REAL,
	0, # squash_yellow_ct REAL,
	0, # asparagus_bnch REAL,
	1, # greenbean_cup REAL,
	0, # tomato_cherry_cup REAL,
	0, # pepper_red_bell_ct REAL,
	1, # pepper_green_bell_ct REAL,
	1, # pepper_serrano_ct REAL,
	0, # herb_basil_cup REAL,
	0, # herb_parsley_cup REAL,
	0, # herb_cilantro_cup REAL,
	0, # quinoa_cup REAL,
	0, # lentil_cup REAL,
	0, # sugar_white_cup REAL,
	0.1, # sugar_brown_cup REAL,
	0, # flour_ap_cup REAL,
	0, # lentil_yellow_cup REAL,
	0, # rice_arborio_cup REAL,
	0.1, # red_pepper_flakes_tb REAL,
	0.1, # pepper_black_tb REAL,
	0, # garlic_powder_tb REAL,
	1, # curry_powder_tb REAL,
	0, # blend_italian_tb REAL,
	0, # salt_kosher_tb REAL,
	0.2, # salt_sea_tb REAL,
	0, # sausage_italian_lb REAL,
	29, # can_chickpea_oz REAL,
	14.5, # can_tomatoes_diced_oz REAL,
	2, # broth_vegetable_cup REAL,
	0, # cond_mustard_dijon_cup REAL,
	1, # oil_olive_tb REAL,
	0, # oil_canola_tb REAL,	
	0, # vinegar_red_wine_cup REAL,
	0, # vinegar_balsamic_cup REAL,
	0, # pasta_short_oz REAL,
	0, # chocolate_dark_oz REAL,
	8, # ethnic_coconut_milk_oz REAL,
	0, # butter_unsalted_cup REAL,
	0, # eggs_ct REAL,
	0, # cheese_parm_regg_tb REAL,
	0, # cheese_romano_cup REAL,
	0, # wine_white_dry_cup REAL,
	1 # recipe_id INTEGER --> Slow-Cooker Vegetable Chickpea Curry
	],

	[
	0, # spinach_baby_bnch REAL,
	0, # celery_hd REAL,
	0, # green_onion_ct REAL,
	0, # lime_ct REAL,
	1, # lemon_ct REAL,
	0.5, # onion_yellow_ct REAL,
	0, # onion_red_ct REAL,
	0, # potato_sweet_ct REAL,
	0, # potato_red_ct REAL,
	2, # garlic_clv REAL,
	0, # broccoli_ct REAL,
	1, # carrot_ct REAL,
	1, # squash_zucchini_ct REAL,
	0, # leeks_ct REAL,
	0, # ginger_inch REAL,
	1, # squash_yellow_ct REAL,
	0.5, # asparagus_bnch REAL,
	1, # greenbean_cup REAL,
	1, # tomato_cherry_cup REAL,
	1, # pepper_red_bell_ct REAL,
	0, # pepper_green_bell_ct REAL,
	0, # pepper_serrano_ct REAL,
	0.3, # herb_basil_cup REAL,
	0.3, # herb_parsley_cup REAL,
	0, # herb_cilantro_cup REAL,
	0, # quinoa_cup REAL,
	0, # lentil_cup REAL,
	0, # sugar_white_cup REAL,
	0, # sugar_brown_cup REAL,
	0, # flour_ap_cup REAL,
	0, # lentil_yellow_cup REAL,
	0, # rice_arborio_cup REAL,
	0, # red_pepper_flakes_tb REAL,
	0.1, # pepper_black_tb REAL,
	0, # garlic_powder_tb REAL,
	0, # curry_powder_tb REAL,
	1, # blend_italian_tb REAL,
	0, # salt_kosher_tb REAL,
	0.1, # salt_sea_tb REAL,
	0, # sausage_italian_lb REAL,
	0, # can_chickpea_oz REAL,
	0, # can_tomatoes_diced_oz REAL,
	0, # broth_vegetable_cup REAL,
	0, # cond_mustard_dijon_cup REAL,
	4, # oil_olive_tb REAL,
	0, # oil_canola_tb REAL,	
	0, # vinegar_red_wine_cup REAL,
	0.25, # vinegar_balsamic_cup REAL,
	12, # pasta_short_oz REAL,
	0, # chocolate_dark_oz REAL,
	0, # ethnic_coconut_milk_oz REAL,
	0.1, # butter_unsalted_cup REAL,
	0, # eggs_ct REAL,
	0, # cheese_parm_regg_tb REAL,
	0.5, # cheese_romano_cup REAL,
	0, # wine_white_dry_cup REAL,
	2 # recipe_id INTEGER --> No-Cream Pasta Primavera
	],

	[
	7, # spinach_baby_bnch REAL,
	0, # celery_hd REAL,
	0, # green_onion_ct REAL,
	0, # lime_ct REAL,
	0, # lemon_ct REAL,
	1, # onion_yellow_ct REAL,
	0, # onion_red_ct REAL,
	0, # potato_sweet_ct REAL,
	0, # potato_red_ct REAL,
	0, # garlic_clv REAL,
	0, # broccoli_ct REAL,
	0, # carrot_ct REAL,
	0, # squash_zucchini_ct REAL,
	0, # leeks_ct REAL,
	0, # ginger_inch REAL,
	0, # squash_yellow_ct REAL,
	0, # asparagus_bnch REAL,
	0, # greenbean_cup REAL,
	0, # tomato_cherry_cup REAL,
	0, # pepper_red_bell_ct REAL,
	0, # pepper_green_bell_ct REAL,
	0, # pepper_serrano_ct REAL,
	0, # herb_basil_cup REAL,
	0, # herb_parsley_cup REAL,
	0, # herb_cilantro_cup REAL,
	0, # quinoa_cup REAL,
	0, # lentil_cup REAL,
	0, # sugar_white_cup REAL,
	0, # sugar_brown_cup REAL,
	0, # flour_ap_cup REAL,
	0, # lentil_yellow_cup REAL,
	1, # rice_arborio_cup REAL,
	0, # red_pepper_flakes_tb REAL,
	1, # pepper_black_tb REAL,
	0, # garlic_powder_tb REAL,
	0, # curry_powder_tb REAL,
	0, # blend_italian_tb REAL,
	0, # salt_kosher_tb REAL,
	1, # salt_sea_tb REAL,
	0.75, # sausage_italian_lb REAL,
	0, # can_chickpea_oz REAL,
	28, # can_tomatoes_diced_oz REAL,
	0, # broth_vegetable_cup REAL,
	0, # cond_mustard_dijon_cup REAL,
	1, # oil_olive_tb REAL,
	0, # oil_canola_tb REAL,	
	0, # vinegar_red_wine_cup REAL,
	0, # vinegar_balsamic_cup REAL,
	0, # pasta_short_oz REAL,
	0, # chocolate_dark_oz REAL,
	0, # ethnic_coconut_milk_oz REAL,
	0.2, # butter_unsalted_cup REAL,
	0, # eggs_ct REAL,
	8, # cheese_parm_regg_tb REAL,
	0, # cheese_romano_cup REAL,
	0.5, # wine_white_dry_cup REAL,
	3 # recipe_id INTEGER --> Tomato and Sausage Risotto
	],

	[
	0, # spinach_baby_bnch REAL,
	0, # celery_hd REAL,
	2, # green_onion_ct REAL,
	1, # lime_ct REAL,
	0, # lemon_ct REAL,
	0, # onion_yellow_ct REAL,
	0, # onion_red_ct REAL,
	0, # potato_sweet_ct REAL,
	0, # potato_red_ct REAL,
	0, # garlic_clv REAL,
	0, # broccoli_ct REAL,
	0, # carrot_ct REAL,
	0, # squash_zucchini_ct REAL,
	0, # leeks_ct REAL,
	0, # ginger_inch REAL,
	0, # squash_yellow_ct REAL,
	0, # asparagus_bnch REAL,
	0, # greenbean_cup REAL,
	0, # tomato_cherry_cup REAL,
	0, # pepper_red_bell_ct REAL,
	0, # pepper_green_bell_ct REAL,
	0, # pepper_serrano_ct REAL,
	0, # herb_basil_cup REAL,
	0, # herb_parsley_cup REAL,
	0.2, # herb_cilantro_cup REAL,
	0.5, # quinoa_cup REAL,
	0, # lentil_brown_cup REAL,
	0, # sugar_white_cup REAL,
	0, # sugar_brown_cup REAL,
	0, # flour_ap_cup REAL,
	0.5, # lentil_yellow_cup REAL,
	0, # rice_arborio_cup REAL,
	0, # red_pepper_flakes_tb REAL,
	1, # pepper_black_tb REAL,
	0.1, # garlic_powder_tb REAL,
	0, # curry_powder_tb REAL,
	0, # blend_italian_tb REAL,
	1, # salt_kosher_tb REAL,
	0, # salt_sea_tb REAL,
	0, # sausage_italian_lb REAL,
	0, # can_chickpea_oz REAL,
	0, # can_tomatoes_diced_oz REAL,
	0, # broth_vegetable_cup REAL,
	0.1, # cond_mustard_dijon_cup REAL,
	0, # oil_olive_tb REAL,
	4, # oil_canola_tb REAL,	
	0.2, # vinegar_red_wine_cup REAL,
	0, # vinegar_balsamic_cup REAL,
	0, # pasta_short_oz REAL,
	0, # chocolate_dark_oz REAL,
	0, # ethnic_coconut_milk_oz REAL,
	0, # butter_unsalted_cup REAL,
	0, # eggs_ct REAL,
	0, # cheese_parm_regg_tb REAL,
	0, # cheese_romano_cup REAL,
	0, # wine_white_dry_cup REAL,
	4 # recipe_id INTEGER --> Lentil Quinoa Salad
	],

	

	[
	0, # spinach_baby_bnch REAL,
	0.5, # celery_hd REAL,
	0, # green_onion_ct REAL,
	0, # lime_ct REAL,
	1, # lemon_ct REAL,
	0, # onion_yellow_ct REAL,
	0, # onion_red_ct REAL,
	2, # potato_sweet_ct REAL,
	0, # potato_red_ct REAL,
	2, # garlic_clv REAL,
	0, # broccoli_ct REAL,
	3, # carrot_ct REAL,
	0, # squash_zucchini_ct REAL,
	2, # leeks_ct REAL,
	4, # ginger_inch REAL,
	0, # squash_yellow_ct REAL,
	0, # asparagus_bnch REAL,
	0, # greenbean_cup REAL,
	0, # tomato_cherry_cup REAL,
	0, # pepper_red_bell_ct REAL,
	0, # pepper_green_bell_ct REAL,
	0, # pepper_serrano_ct REAL,
	0, # herb_basil_cup REAL,
	0, # herb_parsley_cup REAL,
	0.5, # herb_cilantro_cup REAL,
	0, # quinoa_cup REAL,
	0, # lentil_cup REAL,
	0, # sugar_white_cup REAL,
	0, # sugar_brown_cup REAL,
	0, # flour_ap_cup REAL,
	0.75, # lentil_yellow_cup REAL,
	0, # rice_arborio_cup REAL,
	0, # red_pepper_flakes_tb REAL,
	0, # pepper_black_tb REAL,
	0, # garlic_powder_tb REAL,
	0.3, # curry_powder_tb REAL,
	0, # blend_italian_tb REAL,
	1, # salt_kosher_tb REAL,
	0, # salt_sea_tb REAL,
	0, # sausage_italian_lb REAL,
	0, # can_chickpea_oz REAL,
	0, # can_tomatoes_diced_oz REAL,
	0, # broth_vegetable_cup REAL,
	0, # cond_mustard_dijon_cup REAL,
	0, # oil_olive_tb REAL,
	0, # oil_canola_tb REAL,	
	0, # vinegar_red_wine_cup REAL,
	0, # vinegar_balsamic_cup REAL,
	0, # pasta_short_oz REAL,
	0, # chocolate_dark_oz REAL,
	0, # ethnic_coconut_milk_oz REAL,
	0.1, # butter_unsalted_cup REAL,
	0, # eggs_ct REAL,
	0, # cheese_parm_regg_tb REAL,
	0, # cheese_romano_cup REAL,
	0, # wine_white_dry_cup REAL,
	5 # recipe_id INTEGER --> Slow-Cooker Sweet Potato and Lentil Soup
	],

	[

	0, # spinach_baby_bnch REAL,
	0, # celery_hd REAL,
	0, # green_onion_ct REAL,
	0, # lime_ct REAL,
	0, # lemon_ct REAL,
	0, # onion_yellow_ct REAL,
	0, # onion_red_ct REAL,
	0, # potato_sweet_ct REAL,
	0, # potato_red_ct REAL,
	0, # garlic_clv REAL,
	0, # broccoli_ct REAL,
	0, # carrot_ct REAL,
	0, # squash_zucchini_ct REAL,
	0, # leeks_ct REAL,
	0, # ginger_inch REAL,
	0, # squash_yellow_ct REAL,
	0, # asparagus_bnch REAL,
	0, # greenbean_cup REAL,
	0, # tomato_cherry_cup REAL,
	0, # pepper_red_bell_ct REAL,
	0, # pepper_green_bell_ct REAL,
	0, # pepper_serrano_ct REAL,
	0, # herb_basil_cup REAL,
	0, # herb_parsley_cup REAL,
	0, # herb_cilantro_cup REAL,
	0, # quinoa_cup REAL,
	0, # lentil_cup REAL,
	1.3, # sugar_white_cup REAL,
	0, # sugar_brown_cup REAL,
	0.1, # flour_ap_cup REAL,
	0, # lentil_yellow_cup REAL,
	0, # rice_arborio_cup REAL,
	0, # red_pepper_flakes_tb REAL,
	0, # pepper_black_tb REAL,
	0, # garlic_powder_tb REAL,
	0, # curry_powder_tb REAL,
	0, # blend_italian_tb REAL,
	0, # salt_kosher_tb REAL,
	0, # salt_sea_tb REAL,
	0, # sausage_italian_lb REAL,
	0, # can_chickpea_oz REAL,
	0, # can_tomatoes_diced_oz REAL,
	0, # broth_vegetable_cup REAL,
	0, # cond_mustard_dijon_cup REAL,
	0, # oil_olive_tb REAL,
	0, # oil_canola_tb REAL,	
	0, # vinegar_red_wine_cup REAL,
	0, # vinegar_balsamic_cup REAL,
	0, # pasta_short_oz REAL,
	7, # chocolate_dark_oz REAL,
	0, # ethnic_coconut_milk_oz REAL,
	0.5, # butter_unsalted_cup REAL,
	5, # eggs_ct REAL,
	0, # cheese_parm_regg_tb REAL,
	0, # cheese_romano_cup REAL,
	0, # wine_white_dry_cup REAL,
	6 # recipe_id INTEGER --> Almost Flourless Chocolate Cake
	],

	[
	0, # spinach_baby_bnch REAL,
	0, # celery_hd REAL,
	0, # green_onion_ct REAL,
	0, # lime_ct REAL,
	0.5, # lemon_ct REAL,
	0, # onion_yellow_ct REAL,
	0.5, # onion_red_ct REAL,
	0, # potato_sweet_ct REAL,
	0, # potato_red_ct REAL,
	3, # garlic_clv REAL,
	1, # broccoli_ct REAL,
	0, # carrot_ct REAL,
	0, # squash_zucchini_ct REAL,
	0, # leeks_ct REAL,
	0, # ginger_inch REAL,
	0, # squash_yellow_ct REAL,
	0, # asparagus_bnch REAL,
	0, # greenbean_cup REAL,
	0, # tomato_cherry_cup REAL,
	0, # pepper_red_bell_ct REAL,
	0, # pepper_green_bell_ct REAL,
	0, # pepper_serrano_ct REAL,
	0, # herb_basil_cup REAL,
	0, # herb_parsley_cup REAL,
	0, # herb_cilantro_cup REAL,
	0, # quinoa_cup REAL,
	0, # lentil_cup REAL,
	0, # sugar_white_cup REAL,
	0, # sugar_brown_cup REAL,
	0, # flour_ap_cup REAL,
	0, # lentil_yellow_cup REAL,
	0, # rice_arborio_cup REAL,
	0.3, # red_pepper_flakes_tb REAL,
	1, # pepper_black_tb REAL,
	0, # garlic_powder_tb REAL,
	0, # curry_powder_tb REAL,
	0, # blend_italian_tb REAL,
	0.3, # salt_kosher_tb REAL,
	0, # salt_sea_tb REAL,
	0, # sausage_italian_lb REAL,
	0, # can_chickpea_oz REAL,
	0, # can_tomatoes_diced_oz REAL,
	0, # broth_vegetable_cup REAL,
	0, # cond_mustard_dijon_cup REAL,
	7, # oil_olive_tb REAL,
	0, # oil_canola_tb REAL,	
	0, # vinegar_red_wine_cup REAL,
	0, # vinegar_balsamic_cup REAL,
	0, # pasta_short_oz REAL,
	0, # chocolate_dark_oz REAL,
	0, # ethnic_coconut_milk_oz REAL,
	0, # butter_unsalted_cup REAL,
	10, # eggs_ct REAL,
	2.5, # cheese_parm_regg_tb REAL,
	0, # cheese_romano_cup REAL,
	0, # wine_white_dry_cup REAL,
	7 # recipe_id INTEGER --> Slow-Baked Broccoli Frittata
	]
]

recipes_db.execute(create_recipe_table_cmd)

seed_recipes_db(recipes_db, recipes)

recipes_db.execute(create_ingredients_table_cmd)

seed_ingredients_db(recipes_db, ingredients)
